github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-cloud-service-common
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-acceptance-tests
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-dependencies
      branch: 7.0.x
      useSinglePullRequest: true
